CREATE TABLE stg_receipt_items AS
SELECT
    jsonb_array_elements(r.receipt_items)->>'barcode' AS item_barcode,
    jsonb_array_elements(r.receipt_items)->>'brandCode' AS item_brand_code,
    jsonb_array_elements(r.receipt_items)->>'competitiveProduct' AS item_competitive_product,
    jsonb_array_elements(r.receipt_items)->>'competitorRewardsGroup' AS item_competitor_rewards_group,
    jsonb_array_elements(r.receipt_items)->>'deleted' AS item_deleted,
    jsonb_array_elements(r.receipt_items)->>'description' AS item_description,
    jsonb_array_elements(r.receipt_items)->>'discountedItemPrice' AS discounted_item_price,
    jsonb_array_elements(r.receipt_items)->>'finalPrice' AS item_final_price,
    jsonb_array_elements(r.receipt_items)->>'itemNumber' AS item_number,
    jsonb_array_elements(r.receipt_items)->>'itemPrice' AS item_price,
    jsonb_array_elements(r.receipt_items)->>'metabriteCampaignId' AS item_metabrite_campaign_id,
    jsonb_array_elements(r.receipt_items)->>'needsFetchReview' AS item_needs_fetch_review,
    jsonb_array_elements(r.receipt_items)->>'needsFetchReviewReason' AS item_needs_fetch_review_reason,
    jsonb_array_elements(r.receipt_items)->>'originalFinalPrice' AS item_original_final_price,
    jsonb_array_elements(r.receipt_items)->>'originalMetaBriteBarcode' AS item_original_meta_brite_barcode,
    jsonb_array_elements(r.receipt_items)->>'originalMetaBriteDescription' AS item_original_meta_brite_description,
    jsonb_array_elements(r.receipt_items)->>'originalMetaBriteItemPrice' AS item_original_meta_brite_item_price,
    jsonb_array_elements(r.receipt_items)->>'originalMetaBriteQuantityPurchased' AS item_original_meta_brite_quantity_purchased,
    jsonb_array_elements(r.receipt_items)->>'originalReceiptItemText' AS item_original_receipt_item_text,
    jsonb_array_elements(r.receipt_items)->>'priceAfterCoupon' AS item_price_after_coupon,
    jsonb_array_elements(r.receipt_items)->>'partnerItemId' AS item_partner_item_id,
    jsonb_array_elements(r.receipt_items)->>'pointsEarned' AS item_points_earned,
    jsonb_array_elements(r.receipt_items)->>'pointsNotAwardedReason' AS item_points_not_awarded_reason,
    jsonb_array_elements(r.receipt_items)->>'pointsPayerId' AS item_points_payer_id,
    jsonb_array_elements(r.receipt_items)->>'preventTargetGapPoints' AS item_prevent_target_gap_points,
    jsonb_array_elements(r.receipt_items)->>'quantityPurchased' AS item_quantity_purchased,
    jsonb_array_elements(r.receipt_items)->>'rewardsGroup' AS item_rewards_group,
    jsonb_array_elements(r.receipt_items)->>'rewardsProductPartnerId' AS item_rewards_product_partner_id,
    jsonb_array_elements(r.receipt_items)->>'targetPrice' AS item_target_price,
    jsonb_array_elements(r.receipt_items)->>'userFlaggedBarcode' AS item_user_flagged_barcode,
    jsonb_array_elements(r.receipt_items)->>'userFlaggedDescription' AS item_user_flagged_description,
    jsonb_array_elements(r.receipt_items)->>'userFlaggedNewItem' AS item_user_flagged_new_item,
    jsonb_array_elements(r.receipt_items)->>'userFlaggedPrice' AS item_user_flagged_price,
    jsonb_array_elements(r.receipt_items)->>'userFlaggedQuantity' AS item_user_flagged_quantity
FROM stg_receipts AS r;